# Generated by Django 3.2.7 on 2021-09-28 14:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import wagtail.search.index


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_unit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('no_student', models.CharField(max_length=100, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Enter a numeric value', regex='^[0-9]+$')], verbose_name='student number')),
                ('academic_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic_unit.academicunit', verbose_name='Academic Unit')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
