# Generated by Django 3.2.7 on 2021-09-28 14:53

from django.db import migrations, models
import django.db.models.deletion
import wagtail.search.index


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Academic Unit Name')),
                ('little_name', models.CharField(max_length=100, unique=True, verbose_name='Abbreviation Name')),
                ('level', models.CharField(choices=[('MS', 'HighSchool'), ('S', 'University'), ('DAE', 'DAE')], default='S', max_length=3, verbose_name='Level')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Academic Unit Logo')),
            ],
            options={
                'verbose_name': 'Academic Unit',
                'verbose_name_plural': 'Academic Units',
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
